core/core/urls.py
# social_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from myapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.login, name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path('', include('social_django.urls', namespace='social')),
    path("", include('myapp.urls', namespace="myapp")),
    path('forms/', include('forms.urls', namespace="forms")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/forms/urls.py
from myapp import views
from django.urls import re_path
from . import views

from django.urls import path

app_name = 'forms'

urlpatterns = [

    path('forms/',views.image, name='forms'),
    

]

core/myapp/urls.py
from django.urls import path, include
from myapp import views
from django.contrib.auth import views as auth_views
from django.urls import re_path

app_name = 'myapp'


urlpatterns = [

    re_path("home/", views.home, name="home"),
    re_path("account/", views.account, name="account"),
    re_path("index/", views.index, name="index"),
]

core/forms/models.py
from django.db import models

class Image(models.Model):
    uname = models.CharField(max_length=200)
    age = models.IntegerField(verbose_name = 'Age')
    gender = models.CharField(max_length=200, verbose_name = 'Gender')
    about_me = models.TextField(verbose_name='About me', blank=True,null=True)
    image = models.ImageField(upload_to='images',blank=True,null=True)
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = [ 'date_added' ]

    def __str__(self):
        return self.uname

core/myapp/models.py
from django.db import models

# Create your models here.

core/forms/admin.py
from django.contrib import admin
from forms.models import Image
# Register your models here.
admin.site.register(Image)

core/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

core/forms/forms.py
from django import forms
from forms.models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('uname','age',"gender","about_me","image",)

core/forms/tests.py
from django.test import TestCase

# Create your tests here.

core/forms/views.py
from django.shortcuts import render
from forms.forms import ImageForm
from forms.models import Image


def image(request):
    """Process images uploaded by users"""
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img = form.instance
            return render(request, 'forms.html', {'form': form,'img': img})
    else:
        form = ImageForm()
    return render(request, 'forms.html', {'form': form, })

core/myapp/views.py
from forms.models import Image
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# Create your views here.
def login(request):
    return render(request, 'login.html')


@login_required
def home(request):
    return render(request, 'home.html')
def account(request):
    return render(request, 'account.html')

def index(request):
    names = Image.objects.all().order_by("-date_added")
    return render(request, 'home.html', {"names":names})

core/forms/templates/forms.html
{% extends 'home.html' %}
{% block title %} Forms {% endblock %}
{% load static %}

{% block content %}

<div class="container bg-dark">
  <div class="row" style="margin:10%;padding:0;">
    <div class="col-12">

    <form method="post" enctype="multipart/form-data" style="margin-top:5%;padding:0;">

      {% if img %}
        {% csrf_token %}
        <div class="alert alert-primary" role="alert">
          Your account history has been updated!
        </div>
      {% endif %}

  {% if form %}
  {% csrf_token %}
  <input class="form-control mb-3" placeholder="Input your Usename"{{form.uname }}
  <input class="form-control mb-3" placeholder="Input your age"{{form.age}}
  <input class="form-control mb-3" placeholder="Input your Gender"{{form.gender}}
  <input class="form-control mb-3" placeholder="Input your About me"{{form.about_me}}
  <input class="form-control mb-3" placeholder="Upload avatar"{{form.image}}

  <button class="btn btn-light type="submit">Update</button>

  {% endif %}

</form>
<br>


<a href="{% url 'myapp:index' %}" >
  <button class="btn btn-danger mb-2">Home</button>
</a>

</div>
</div>
</div>
{% endblock %}

core/myapp/templates/account.html
{% extends 'base.html' %}
{% block title %} Account {% endblock %}
{% load static %}

{% block content %}
<div class="container" style=" margin10%; padding:5%; background-color:#000000; position:relative;">
<div class="row">
  <div class="col-lg-12 mb-3">
    <br>
    <h4 class="text-center text-light">Account Google</h4>
  </div>

      <!-- Add from here -->
  {% for ass in backends.associated %}
    {% if ass.provider == 'google-oauth2' %}
      <div class="col-12 col-md-6">
        <img src="{% static 'image/google.png' %}" alt="" width="400" height="400">
      </div>
      <div class="col-4 social-container mb-2 text-light">
          <p> Provider:  {{ ass.provider }} </p>
          <p> Username:  {{ass.user.last_name}} {{ass.user.first_name}}</p>
          <p> email:<a  href="https://myaccount.google.com/?utm_source=OGB&tab=wk&utm_medium=act">{{ass.uid}}<a> </p>
      </div>
    {% endif %}
  {% endfor %}
  <div class="col-sm-12 mt-2 text-center text-light">
    <a href="{% url 'logout' %}">
    <button class="btn btn-danger ">Logout</button>
    </a>
    <a href="{% url 'myapp:index' %}">
    <button class="btn btn-primary">Home</button>
    </a>
  </div>
      <!-- End here -->
</div>
</div>

<style media="screen">
  .social-container {
  display: flex;
  flex-direction: column;
  justify-content: center;
}
.btn a, .btn a:hover {
  color: white;
  text-decoration: none ;
}
</style>
{% endblock %}

core/myapp/templates/base.html
{% load static %}
<!DOCTYPE html>
 <html lang="en">
   <head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     <meta charset="UTF-8" />
     <meta name="viewport" content="width=device-width, initial-scale=1.0" />
     <meta http-equiv="X-UA-Compatible" content="ie=edge" />
     <link rel="stylesheet" href="{% static 'css/mystyles.css' %}" />
     <title>Social Auth with Django</title>
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

   <body background="{% static 'image/1.png' %}">
     <div class="container-fluid "style="width:80%; height: 100%;" >

                {% block content %}

                {% endblock %}
    </div>

    </body>
</html>

core/myapp/templates/home.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %}
{% load static %}

{% block content %}


<div class="row-12" >

  <nav class="navbar navbar-dark bg-dark"  style = " height:10ex;">
    <a href="{% url 'myapp:index' %}">
      <button class="btn btn-danger ">Home</button>
    </a>
    <a href="{% url 'forms:forms' %}">
      <button class="btn btn-warning ">Input My Account</button>
    </a>

      <a href="{% url 'myapp:account' %}">
        <button class="btn btn-primary ">My Account Google</button>
      </a>
  </nav>
</div>


<div class="container bg-dark"

 style='margin-top:2em;padding:2px; position:relative; display:block;'>

 <div class="row-12" >
   <br>
   <h3><p class = "text-center text-light">My History Account</p></h3>
    <div class="card" style="width: 40rem; margin:0 auto; padding:2px; position:relative; display:block;">


        {% for names in names  %}
          <br>
          <img class="  {% if names.image %}card-img-top border border-dark" src="{{ names.image.url}}  {% endif %}" alt="Card image cap">
            <div class="card-body">

              <p class="card-text text-center text-light bg-dark">Usename: {{ names.uname}}</p>
              <p class="card-text text-center text-light bg-dark" >Gender: {{ names.gender}}</p>
              <p class="card-text text-center text-light bg-dark">Age: {{ names.age}}</p>
              <p class="card-text text-center text-light bg-dark">About me: {{ names.about_me}}</p>

            </div>

        {% endfor %}
      </div>
    </div>
</div>


{% endblock %}

core/myapp/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Sign in {% endblock %}
{% block content %}
<div class="container"
  style="background-color:#4682B4; height:300px; width:100%; top:20%;" >
  <div class= "row" style = "margin-top:28%; padding:20px;">
    <div class="col-md-12">
      <h1 class="text-white text-center mb-1">Please Sign in </h1>
        <div class="card p-5" >
          <a href="{% url "social:begin" "google-oauth2" %}">
            <button class="btn btn-primary  mb-5"
            style = "margin-top:2%; padding:10px; width:100%; height:50%;">Google</button>
          </a>
        </div>
    </div>
  </div>
</div>

{% endblock %}